"DROP TABLE IF EXISTS " +
            "ODONTOLOGO; CREATE TABLE ODONTOLOGO (ID INT AUTO_INCREMENT PRIMARY KEY," +
            " NUM_MATRICULA INT NOT NULL," +
            " NOMBRE VARCHAR(100) NOT NULL," +
            " APELLIDO VARCHAR(100) NOT NULL," +
            ")";